# Generated by Django 5.1.5 on 2025-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/users/%Y/%m/%d/'),
        ),
    ]
